strictness: high

test-warnings: false
doc-warnings: true

max-line-length: 120

autodetect: false

output-format: pylint

pylint:
  disable:
    - too-many-arguments

pydocstyle:
  disable:
    - D203
    - D212
    - D213
    - D406
    - D407

ignore-paths:
  - data/out
  - data/out_func
  - data/templates
  - docs
  - samples

mypy:
  run: true